import { test, expect } from "@playwright/test";
import { quoteAnalysis } from "../../lib/billing/pricing-v6";
for (const locale of ["zh", "en"]) for (const width of [1440, 390]) for (const seconds of [10, 180]) {
  test(`analysis quote and confirmation ${locale} ${width} ${seconds}s`, async ({ page, context }) => {
    await page.setViewportSize({ width, height: 1000 });
    await context.addCookies([{ name: "NEXT_LOCALE", value: locale, domain: "localhost", path: "/" }]);
    const projectId = "11111111-1111-4111-8111-111111111111";
    const taskId = "22222222-2222-4222-8222-222222222222";
    const scenes = seconds === 10 ? [{ id: "1", startUs: 0, endUs: 2000000 }, { id: "2", startUs: 2000000, endUs: 10000000 }] : Array.from({ length: 30 }, (_, i) => ({ id: String(i + 1), startUs: i * 6000000, endUs: (i + 1) * 6000000 }));
    const pricing = { payer: seconds === 180 ? "byok_split" as const : "platform" as const, model: "flash" as const, sourceDurationUs: seconds * 1000000, automaticSplit: true, paidSplitReusable: false, scenes };
    const totalCredits = quoteAnalysis(pricing).credits;
    const singleCredits = quoteAnalysis({ ...pricing, scenes: scenes.slice(0, 1) }).credits;
    let confirmations = 0;
    let quoteRequest: Record<string, unknown> | undefined;
    await page.route("**/api/**", async (route) => {
      const path = new URL(route.request().url()).pathname;
      let body: unknown = {};
      if (path.includes("/auth/get-session")) body = { user: { id: "test", email: "test@example.com", name: "Test" }, session: { id: "test", token: "test", expiresAt: new Date(Date.now() + 3600000).toISOString() } };
      else if (path === "/api/credits/me") body = { commercialConsumptionEnabled: true, balance: 0, mode: "byok", hasUserKieKey: true, trial: { limit: 2, remaining: 0 }, commercial: { enabled: true, credits: 200, rewrites: 20 }, linkImports: { remaining: 10 } };
      else if (path === "/api/models") body = { models: [] };
      else if (path === "/api/workflow/projects") body = route.request().method() === "POST" ? { project: { id: projectId } } : { projects: [] };
      else if (path === "/api/media/resolve-link") body = { mediaUrl: "https://example.com/video.mp4", filename: "linked-video.mp4", mediaType: "video", platform: "douyin", duration: seconds, metadata: { duration: seconds } };
      else if (path === "/api/commercial/analysis") {
        const data = route.request().postDataJSON();
        if (data.action === "prepare") body = { id: "preview", durationUs: pricing.sourceDurationUs, scenes };
        else { quoteRequest = data; body = { id: taskId, ...quoteAnalysis({ ...pricing, scenes: scenes.filter(s => data.sceneIds.includes(s.id)) }) }; }
      } else if (path === `/api/commercial/tasks/${taskId}`) {
        if (route.request().method() === "POST") confirmations++;
        body = { id: taskId, state: "running", credits: 8 };
      }
      await route.fulfill({ json: body });
    });
    await page.goto("/dashboard?tab=analyze");
    await page.getByRole("tab", { name: locale === "zh" ? "粘贴链接" : "Paste link" }).click();
    await page.getByLabel(locale === "zh" ? "视频链接" : "Video link", { exact: true }).fill("https://v.douyin.com/test/");
    const actionRow = page.getByTestId("analysis-action-row");
    const actionBox = await actionRow.getByRole("button").boundingBox();
    const sourceBox = await actionRow.getByRole("combobox").boundingBox();
    expect(actionBox!.x + actionBox!.width).toBeLessThanOrEqual(sourceBox!.x);
    expect(Math.abs(actionBox!.y - sourceBox!.y)).toBeLessThan(2);
    expect(actionBox!.height).toBeLessThanOrEqual(44);
    expect(sourceBox!.height).toBe(actionBox!.height);
    await actionRow.getByRole("combobox").selectOption("byok");
    await actionRow.getByRole("combobox").selectOption("platform");
    if (pricing.payer === "byok_split") await actionRow.getByRole("combobox").selectOption("byok");
    await actionRow.screenshot({ path: `test-results/analysis-action-row-${locale}-${width}-${seconds}s.png` });
    await actionRow.getByRole("button").click();
    const panel = page.getByRole("region", { name: locale === "zh" ? "镜头选择与费用" : "Shots and analysis cost" });
    await expect(panel).toBeVisible();
    await expect(page.getByRole("dialog")).toHaveCount(0);
    await expect(panel.getByRole("combobox")).toHaveCount(0);
    await expect(panel.getByRole("link")).toHaveCount(0);
    await expect(actionRow.getByRole("button")).toBeDisabled();
    await expect(panel.getByRole("combobox", { name: locale === "zh" ? "费用来源" : "Payment source" })).toHaveCount(0);
    await panel.getByRole("button", { name: locale === "zh" ? "读取视频信息" : "Inspect video" }).click();
    await expect(panel.getByText(`${seconds.toFixed(2)}s · ${scenes.length} ${locale === "zh" ? "个镜头" : "shots"}`, { exact: true })).toBeVisible();
    expect(confirmations).toBe(0);
    const all = panel.getByRole("checkbox", { name: locale === "zh" ? "全选" : "Select all", exact: true });
    const first = panel.getByRole("checkbox", { name: locale === "zh" ? "镜头 1" : "Shot 1", exact: true });
    const second = panel.getByRole("checkbox", { name: locale === "zh" ? "镜头 2" : "Shot 2", exact: true });
    await expect(all).toBeChecked();
    await expect(panel.getByText(locale === "zh" ? `预计 ${totalCredits} 积分` : `Estimated ${totalCredits} credits`, { exact: true })).toBeVisible();
    await all.uncheck();
    await expect(first).not.toBeChecked();
    await expect(second).not.toBeChecked();
    await expect(panel.getByRole("button", { name: locale === "zh" ? "获取报价" : "Get quote" })).toBeDisabled();
    await first.check();
    await expect(all).toBeChecked({ indeterminate: true });
    await expect(panel.getByText(locale === "zh" ? `预计 ${singleCredits} 积分` : `Estimated ${singleCredits} credits`, { exact: true })).toBeVisible();
    await panel.getByRole("button", { name: locale === "zh" ? "获取报价" : "Get quote" }).click();
    await expect(panel.getByText(locale === "zh" ? `${singleCredits} 积分` : `${singleCredits} credits`, { exact: true })).toBeVisible();
    expect(quoteRequest).toMatchObject({ sceneIds: ["1"] });
    await expect(first).toBeDisabled();
    await expect(actionRow.getByRole("combobox")).toBeDisabled();
    await panel.getByRole("button", { name: locale === "zh" ? "调整选择" : "Adjust selection" }).click();
    await all.check();
    await expect(first).toBeChecked();
    await expect(second).toBeChecked();
    await panel.getByRole("button", { name: locale === "zh" ? "获取报价" : "Get quote" }).click();
    await expect(panel.getByText(locale === "zh" ? `${totalCredits} 积分` : `${totalCredits} credits`, { exact: true })).toBeVisible();
    expect(quoteRequest).toMatchObject({ payer: pricing.payer, sceneIds: scenes.map(s => s.id) });
    if (pricing.payer === "byok_split") expect(quoteRequest).toMatchObject({ modelId: "analysis-gemini-3-8-flash" });
    expect(confirmations).toBe(0);
    const box = await panel.boundingBox();
    expect(box!.x).toBeGreaterThanOrEqual(0); expect(box!.x + box!.width).toBeLessThanOrEqual(width);
    await panel.screenshot({ path: `test-results/analysis-quote-${locale}-${width}-${seconds}s.png` });
    await panel.getByRole("button", { name: locale === "zh" ? `确认并分析 · ${totalCredits} 积分` : `Confirm analysis · ${totalCredits} credits` }).click();
    await expect.poll(() => confirmations).toBe(1);
  });
}
